### ISSUE TITLE
Enhaced mode - AllocationCallback problems

### ISSUE THREAD

**Issue by acterhd** [nvpro-pipeline/vkcpp#64] opened 2016-03-06 20:08 UTC
I have problems with functions.  For example `createDescriptorSetLayout` require reference to `AllocationCallbacks`, but not possible to make null of this class.

**Comment by mtavenrath** [comment] 2016-03-06 21:41
As written in the README, there's a null reference now for each object

<pre>
    // Sometimes it's necessary to pass a nullptr to a struct. For this case we've added T& null() to all structs T as replacement for nullptr.<br>
device.allocateMemory(allocateInfo, vk::AllocationCallbacks::null());
</pre>

Closing as not a bug.

**Closed by mtavenrath** 2016-03-06 21:41 UTC
