### ISSUE TITLE
DisplayPlaneAlphaFlagBitsKHR used before defined in generated vk_cpp.h

### ISSUE THREAD

**Issue by jgavert** [nvpro-pipeline/vkcpp#17] opened 2016-02-18 00:58 UTC
I built the vkcppgenerator(release build) using cmake & VS 2015 and made myself a vk_cpp.h from the vk.xml (vulkan docs github).

I'm building my project with VS 2015 and I get this error. It's followed by bunch of other errors that are caused by the first one.
`externals\Vulkan\include\vk_cpp.h(11400): error C2065: 'DisplayPlaneAlphaFlagBitsKHR': undeclared identifier`

Now I simply went ahead and moved the enum declaration above the code that tries to use the enum to fix it. Enum was declared 2 thousand lines below where it was tried to be used.

For completeness: DisplayPlaneAlphaFlagBitsKHR was declared on line: 13679
and error was on line 11400 as you can see from above error.

Fixed header part looks like this:

  ```
enum class DisplayPlaneAlphaFlagBitsKHR
  {
    eOpaque = VK_DISPLAY_PLANE_ALPHA_OPAQUE_BIT_KHR,
    eGlobal = VK_DISPLAY_PLANE_ALPHA_GLOBAL_BIT_KHR,
    ePerPixel = VK_DISPLAY_PLANE_ALPHA_PER_PIXEL_BIT_KHR,
    ePerPixelPremultiplied = VK_DISPLAY_PLANE_ALPHA_PER_PIXEL_PREMULTIPLIED_BIT_KHR
  };

  typedef Flags<DisplayPlaneAlphaFlagBitsKHR, VkDisplayPlaneAlphaFlagsKHR> DisplayPlaneAlphaFlagsKHR;
```

I find it strange that there isn't a issue about this already so wondering the reason why I'm getting this.

I've also experienced this on 2 computers now. Fresh cmake installation, vs2015 update 1, up-to-date git clones.

**Comment by mtavenrath** [comment] 2016-02-18 07:18
I cannot reproduce the issue with the official 1.0 vk.xml. Which version did you use to generate the header? Which function references the symbol?

**Comment by jgavert** [comment] 2016-02-18 12:13
I used the official repository https://github.com/KhronosGroup/Vulkan-Docs
from "src/spec" I found the "vk.xml"

So I made small case to repro this:

The folder structure.

```
main.cpp
vk_cpp.h (freshly generated using newest commit be005930965b83da2f11db74a3246a620478f428)
Vulkan/vulkan.h (copied from Vulkan-Docs repository, "src/vulkan")
Vulkan/vk_platform.h (same as above)
```

where main.cpp is

```
#define NOMINMAX
#include <windows.h>
#include <vk_cpp.h>

int WINAPI WinMain(HINSTANCE /*hInstance*/,
	HINSTANCE /*hPrevInstance*/,
	LPSTR /*lpCmdLine*/,
	int /*nCmdShow*/)
{

	return 0;
}
```

Open the folder in command prompt and run the following command:

This command assumes that you have VS2015 and Windows 10 SDK version 10.0.10586.0 installed in default locations.
Command also includes all files from the directory it's run in and tries to build "main.obj"

```
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\cl.exe" "main.cpp" /Z7 /nologo /c /W4 /WX /TP /Zc:inline /Zc:strictStrings /we4062 /we4263 /we4296 /we4555 /we4619 /we4640 /we4826 /we4836 /we4905 /we4906 /fp:fast /D"WIN32_LEAN_AND_MEAN" /D_WIN32 /D__WINDOWS__ /D"_CRT_SECURE_NO_WARNINGS" /D"_WINSOCK_DEPRECATED_NO_WARNINGS"  /Gd /Fo"main.obj" /I"./" /I"C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include/" /I"C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/atlmfc/include/" /I"C:/Program Files (x86)/Windows Kits/10/include/10.0.10586.0/shared" /I"C:/Program Files (x86)/Windows Kits/10/include/10.0.10586.0/ucrt" /I"C:/Program Files (x86)/Windows Kits/10/include/10.0.10586.0/um" /I"C:/Program Files (x86)/Windows Kits/10/include/10.0.10586.0/winrt" /DWIN64 /DDEBUG /D_DEBUG /D_CRTDBG_MAP_ALLOC /MTd /Od /RTC1 /GS /Oy- /GR- /EHsc
```

Now you should get errors where the first one is
```
error C2065: 'DisplayPlaneAlphaFlagBitsKHR': undeclared identifier
```

**Comment by mtavenrath** [comment] 2016-02-18 13:41
Did you apply the change mentioned in the readme?

--- d:\git\vulkan\src\spec\vk.xml       2016-02-18 09:31:01.641166300 +0100
+++ vk_orig.xml 2016-02-18 14:33:57.044875100 +0100
@@ -4969,7 +4969,6 @@
                 <enum value="&quot;VK_KHR_display&quot;"                name="VK_KHR_DISPLAY_EXTENSION_NAME"/>
                 <enum offset="0" extends="VkStructureType"              name="VK_STRUCTURE_TYPE_DISPLAY_MODE_CREATE_INFO_KHR"/>
                 <enum offset="1" extends="VkStructureType"              name="VK_STRUCTURE_TYPE_DISPLAY_SURFACE_CREATE_INFO_KHR"/>
+                <type name="VkDisplayPlaneAlphaFlagsKHR"/>
                 <type name="VkDisplayPlaneAlphaFlagBitsKHR"/>
                 <type name="VkDisplayPropertiesKHR"/>
                 <type name="VkDisplayModeParametersKHR"/>

**Comment by jgavert** [comment] 2016-02-18 13:51
asdfg...

Yes, that fixes the issue. Thanks!

("Alternative Initialization of Structs" Yes, this is very nice feature!)
Thanks for the c++ api!

**Comment by mtavenrath** [comment] 2016-02-18 14:02
Not an issue, closing.

**Closed by mtavenrath** 2016-02-18 14:02 UTC
